### ISSUE TITLE
Wie kann der KommentarLeser kompiliert / verwendet werden?

### ISSUE THREAD

**Issue by aisbergde** [KommentarLeser/KommentarLeser#1]
Was muss man machen, um den KommentarLeser verwenden zu können? Gibt es den als kompiliertes Programm?

Ich habe zwar das Projekt geklont, weiß nun aber nicht weiter, da ich mich noch nie mit C# Programmierung beschäftigt habe. Irgendwie muss das ja nun kompiliert werden, bevor man es verwenden kann. Ich weiß aber nicht, wie. Ein Video, wie man C# mit Visual Studio Code kompiliert, habe ich mir angeschaut das scheint aber eine ganze Wissenschaft zu sein. 

Leider gibt die Suche auf vineyardsaker.de auch keine Ergebnisse für den KommentarLeser. 
Eine Suchmaschine liefert noch:
Linuphilus
2. OKTOBER 2018 UM 21:50 UHR
Vielleicht meinen Sie den KommentarLeser:
https://github.com/KommentarLeser/KommentarLeser

Auch habe ich noch einen Kommentar von 2016 gefunden, die dort angegebenen Download-Links über ftp funktionieren aber nicht mehr, da sicher die DynDNS abgelaufen ist:
KommentarLeser
22. OKTOBER 2016 UM 18:59 UHR
So, mein kleiner KommentarLeser läuft jetzt auch auf dem neuen Saker. Hoffentlich Fehlerfrei.

**Comment by KommentarLeser** [comment]
Hallo Germo,

Ihre Nachricht ist bei mir im Spam gelandet, daher die späte Antwort.

Die aktuelle Version liegt auf meinem Yandex:

https://yadi.sk/d/MNyuMpJlBeIqSg

Unter Windows einfach in ein Verzeichnis Ihrer Wahl auspacken und
starten sollte für die meisten Rechner reichen. Wenn nicht, muß
wahrscheinlich noch eine aktuelle Version von .NET installiert werden.

Unter Linux/IOS braucht es statt .NET Mono:

http://www.mono-project.com/

Ich hoffe, das hilft.


Gruß

   Caligulaminus


Am 09.11.2019 um 22:49 schrieb Germo Görtz - notifications@github.com:

**Comment by aisbergde** [comment]
Ja, so funktioniert das!

Wäre es nicht eine gute Idee, hier auch im GitHub kompilierten Code abzulegen? Dann kann sich das jeder bei Bedarf direkt hier aus Github herunter laden.

Und hier auf der Seite sollte es einen Link zu diesem Projekt geben. Da müssen wir den Dorfpolizisten mal bitten:
https://www.vineyardsaker.de/technisches/
